name: Deploy my Lambda Function

# trigger on all push events to main branch
on: 
  push:
    branches:
      - main
    paths:
      - 'notes/*'
  workflow_dispatch:
    inputs:
      clean:
        description: Clean serverless deployment for nodeJS
        required: false
        default: ''
      cache:
         description: Clean npm Cache
         required: false
         default: ''
      deploy:
         description: Deploy branch
         required: false
         default: ''
defaults:
  run:
    working-directory: notes
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '12.18.0'
      - name: Flush Cache
        if: github.event.inputs.cache != ''
        run: npm cache clean -f
      - name: Installing Root Node Dependencies
        run: npm install
        working-directory: .
      - name: Installing Node Dependencies
        run: npm install
#     - name: Clean
#       if: github.event.inputs.clean != ''
#       run: npx serverless remove -v
      - name: Deploy
#       if: github.ref == 'refs/heads/master' || github.event.inputs.deploy != ''
        run: npx serverless@2.53.1 deploy -v
        
